/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tema.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
tema_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *login_1_arg;
		char *logout_1_arg;
		struct sensor_data add_1_arg;
		struct sensor_data update_1_arg;
		struct entry_info del_1_arg;
		struct entry_info read_1_arg;
		struct entry_info get_stat_1_arg;
		u_long get_stat_all_1_arg;
		char *get_client_id_1_arg;
		struct entry_info find_entry_1_arg;
		struct user_data store_1_arg;
		struct user_data load_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case LOGIN:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_u_long;
		local = (char *(*)(char *, struct svc_req *)) login_1_svc;
		break;

	case LOGOUT:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_u_long;
		local = (char *(*)(char *, struct svc_req *)) logout_1_svc;
		break;

	case ADD:
		_xdr_argument = (xdrproc_t) xdr_sensor_data;
		_xdr_result = (xdrproc_t) xdr_u_long;
		local = (char *(*)(char *, struct svc_req *)) add_1_svc;
		break;

	case UPDATE:
		_xdr_argument = (xdrproc_t) xdr_sensor_data;
		_xdr_result = (xdrproc_t) xdr_u_long;
		local = (char *(*)(char *, struct svc_req *)) update_1_svc;
		break;

	case DEL:
		_xdr_argument = (xdrproc_t) xdr_entry_info;
		_xdr_result = (xdrproc_t) xdr_u_long;
		local = (char *(*)(char *, struct svc_req *)) del_1_svc;
		break;

	case READ:
		_xdr_argument = (xdrproc_t) xdr_entry_info;
		_xdr_result = (xdrproc_t) xdr_sensor_data;
		local = (char *(*)(char *, struct svc_req *)) read_1_svc;
		break;

	case GET_STAT:
		_xdr_argument = (xdrproc_t) xdr_entry_info;
		_xdr_result = (xdrproc_t) xdr_get_stat_entry;
		local = (char *(*)(char *, struct svc_req *)) get_stat_1_svc;
		break;

	case GET_STAT_ALL:
		_xdr_argument = (xdrproc_t) xdr_u_long;
		_xdr_result = (xdrproc_t) xdr_get_stat_entries;
		local = (char *(*)(char *, struct svc_req *)) get_stat_all_1_svc;
		break;

	case GET_CLIENT_ID:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_u_long;
		local = (char *(*)(char *, struct svc_req *)) get_client_id_1_svc;
		break;

	case GET_STATUS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) get_status_1_svc;
		break;

	case FIND_ENTRY:
		_xdr_argument = (xdrproc_t) xdr_entry_info;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) find_entry_1_svc;
		break;

	case STORE:
		_xdr_argument = (xdrproc_t) xdr_user_data;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) store_1_svc;
		break;

	case LOAD:
		_xdr_argument = (xdrproc_t) xdr_user_data;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) load_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (TEMA_PROG, TEMA_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, TEMA_PROG, TEMA_VERS, tema_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (TEMA_PROG, TEMA_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, TEMA_PROG, TEMA_VERS, tema_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (TEMA_PROG, TEMA_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
