/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tema.h"

bool_t
xdr_sensor_data (XDR *xdrs, sensor_data *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->client_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->data_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->no_values))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->client_id);
		IXDR_PUT_LONG(buf, objp->data_id);
		IXDR_PUT_LONG(buf, objp->no_values);
		}
		 if (!xdr_array (xdrs, (char **)&objp->values.values_val, (u_int *) &objp->values.values_len, ~0,
			sizeof (float), (xdrproc_t) xdr_float))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->client_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->data_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->no_values))
				 return FALSE;

		} else {
		objp->client_id = IXDR_GET_U_LONG(buf);
		objp->data_id = IXDR_GET_LONG(buf);
		objp->no_values = IXDR_GET_LONG(buf);
		}
		 if (!xdr_array (xdrs, (char **)&objp->values.values_val, (u_int *) &objp->values.values_len, ~0,
			sizeof (float), (xdrproc_t) xdr_float))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_long (xdrs, &objp->client_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->data_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->no_values))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->values.values_val, (u_int *) &objp->values.values_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_entry_info (XDR *xdrs, entry_info *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->client_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->data_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_stat_entry (XDR *xdrs, get_stat_entry *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->minim))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->maxim))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->medie))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->mediana))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->error))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_stat_entries (XDR *xdrs, get_stat_entries *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->values.values_val, (u_int *) &objp->values.values_len, ~0,
		sizeof (get_stat_entry), (xdrproc_t) xdr_get_stat_entry))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_user_data (XDR *xdrs, user_data *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->client_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nume, ~0))
		 return FALSE;
	return TRUE;
}
