/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEMA_H_RPCGEN
#define _TEMA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sensor_data {
	u_long client_id;
	int data_id;
	int no_values;
	struct {
		u_int values_len;
		float *values_val;
	} values;
};
typedef struct sensor_data sensor_data;

struct entry_info {
	u_long client_id;
	int data_id;
};
typedef struct entry_info entry_info;

struct get_stat_entry {
	float minim;
	float maxim;
	float medie;
	float mediana;
	int error;
};
typedef struct get_stat_entry get_stat_entry;

struct get_stat_entries {
	struct {
		u_int values_len;
		struct get_stat_entry *values_val;
	} values;
};
typedef struct get_stat_entries get_stat_entries;

struct user_data {
	u_long client_id;
	char *nume;
};
typedef struct user_data user_data;

#define TEMA_PROG 1
#define TEMA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOGIN 1
extern  u_long * login_1(char **, CLIENT *);
extern  u_long * login_1_svc(char **, struct svc_req *);
#define LOGOUT 2
extern  u_long * logout_1(char **, CLIENT *);
extern  u_long * logout_1_svc(char **, struct svc_req *);
#define ADD 3
extern  u_long * add_1(struct sensor_data *, CLIENT *);
extern  u_long * add_1_svc(struct sensor_data *, struct svc_req *);
#define UPDATE 4
extern  u_long * update_1(struct sensor_data *, CLIENT *);
extern  u_long * update_1_svc(struct sensor_data *, struct svc_req *);
#define DEL 5
extern  u_long * del_1(struct entry_info *, CLIENT *);
extern  u_long * del_1_svc(struct entry_info *, struct svc_req *);
#define READ 6
extern  struct sensor_data * read_1(struct entry_info *, CLIENT *);
extern  struct sensor_data * read_1_svc(struct entry_info *, struct svc_req *);
#define GET_STAT 7
extern  struct get_stat_entry * get_stat_1(struct entry_info *, CLIENT *);
extern  struct get_stat_entry * get_stat_1_svc(struct entry_info *, struct svc_req *);
#define GET_STAT_ALL 8
extern  struct get_stat_entries * get_stat_all_1(u_long *, CLIENT *);
extern  struct get_stat_entries * get_stat_all_1_svc(u_long *, struct svc_req *);
#define GET_CLIENT_ID 9
extern  u_long * get_client_id_1(char **, CLIENT *);
extern  u_long * get_client_id_1_svc(char **, struct svc_req *);
#define GET_STATUS 10
extern  void * get_status_1(void *, CLIENT *);
extern  void * get_status_1_svc(void *, struct svc_req *);
#define FIND_ENTRY 11
extern  int * find_entry_1(struct entry_info *, CLIENT *);
extern  int * find_entry_1_svc(struct entry_info *, struct svc_req *);
#define STORE 12
extern  int * store_1(struct user_data *, CLIENT *);
extern  int * store_1_svc(struct user_data *, struct svc_req *);
#define LOAD 13
extern  int * load_1(struct user_data *, CLIENT *);
extern  int * load_1_svc(struct user_data *, struct svc_req *);
extern int tema_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOGIN 1
extern  u_long * login_1();
extern  u_long * login_1_svc();
#define LOGOUT 2
extern  u_long * logout_1();
extern  u_long * logout_1_svc();
#define ADD 3
extern  u_long * add_1();
extern  u_long * add_1_svc();
#define UPDATE 4
extern  u_long * update_1();
extern  u_long * update_1_svc();
#define DEL 5
extern  u_long * del_1();
extern  u_long * del_1_svc();
#define READ 6
extern  struct sensor_data * read_1();
extern  struct sensor_data * read_1_svc();
#define GET_STAT 7
extern  struct get_stat_entry * get_stat_1();
extern  struct get_stat_entry * get_stat_1_svc();
#define GET_STAT_ALL 8
extern  struct get_stat_entries * get_stat_all_1();
extern  struct get_stat_entries * get_stat_all_1_svc();
#define GET_CLIENT_ID 9
extern  u_long * get_client_id_1();
extern  u_long * get_client_id_1_svc();
#define GET_STATUS 10
extern  void * get_status_1();
extern  void * get_status_1_svc();
#define FIND_ENTRY 11
extern  int * find_entry_1();
extern  int * find_entry_1_svc();
#define STORE 12
extern  int * store_1();
extern  int * store_1_svc();
#define LOAD 13
extern  int * load_1();
extern  int * load_1_svc();
extern int tema_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sensor_data (XDR *, sensor_data*);
extern  bool_t xdr_entry_info (XDR *, entry_info*);
extern  bool_t xdr_get_stat_entry (XDR *, get_stat_entry*);
extern  bool_t xdr_get_stat_entries (XDR *, get_stat_entries*);
extern  bool_t xdr_user_data (XDR *, user_data*);

#else /* K&R C */
extern bool_t xdr_sensor_data ();
extern bool_t xdr_entry_info ();
extern bool_t xdr_get_stat_entry ();
extern bool_t xdr_get_stat_entries ();
extern bool_t xdr_user_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEMA_H_RPCGEN */
