version: "3.8"

services:
  laborator2-api:
    environment:
      NODE_ENV: staging
      PGUSER_SECRET: username-secret
      PGPASSWORD_SECRET: password-secret
    secrets:
      - username-secret
      - password-secret

  laborator2-db:
    environment:
      POSTGRES_USER_FILE: /run/secrets/username-secret
      POSTGRES_PASSWORD_FILE: /run/secrets/password-secret
    secrets:
      - username-secret
      - password-secret
    
secrets:
  username-secret:
    file: './secrets/user-secret.txt'
  password-secret:
    file: './secrets/password-secret.txt'
