version: '3.8'

services:
  app:
    build: ./
    container_name: "tema2-sprc_app"
    ports:
      - "3000:3000"
    restart: always
    links:
      - mongo
    volumes:
      - /tema2-sprc/node_modules

  mongo:
    image: mongo
    container_name: "tema2-sprc_mongo"
    environment:
      MONGO_DATABASE: db-sprc
    ports:
      - "27018:27017"
    volumes:
      - mongo_database:/data/db

volumes:
  mongo_database:
