version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: "tema3-sprc_mosquitto"
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf  
