version: '3.8'

services:
  app:
    build: ./
    ports:
      - "3000:3000"
    restart: always
    links:
      - mongo
    volumes:
      - ./:/tema2-sprc
      - /tema2-sprc/node_modules

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_database:/data/db

volumes:
  mongo_database:
