version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - monitor_network
      
  grafana:
    image: 127.0.0.1:5000/sprc3
    ports:
      - 3000:3000
    networks:
      - monitor_network
    volumes:
      - grafana-volume:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: asistent
      GF_SECURITY_ADMIN_PASSWORD: grafanaSPRC2020

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    networks:
      - monitor_network
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      INFLUXDB_DB: db1
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: student
      INFLUX_USER_PASSWORD: student

  adaptor:
    image: adaptor
    networks:
      - monitor_network

  client:
    image: client
    networks:
      - monitor_network
      
networks:
  monitor_network:

volumes:
  grafana-volume:
  influxdb-volume:
