/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "warmup.h"

int *
get_sum_1_svc(struct elem *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Computing sum on server...\n");
	result = argp->x + argp->y;

	return &result;
}
