/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "warmup.h"


void
warmup_prog_1(char *host, int x, int y)
{
	CLIENT *clnt;
	int  *result_1;
	struct elem  get_sum_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, WARMUP_PROG, WARMUP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	get_sum_1_arg.x = x;
	get_sum_1_arg.y = y;
	result_1 = get_sum_1(&get_sum_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("sum: %d\n", *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server_host x y\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int x = atoi(argv[2]);
	int y = atoi(argv[3]);
	warmup_prog_1 (host, x, y);
exit (0);
}
