version: "3.8"

services:
  gateway:
    build: api-gateway-microservice/
    environment:
      BOOKS_SERVICE_API_ROUTE: books-service/api
      NODE_ENV: development
    ports:
      - "3000:80"
    networks:
      - laborator3-gateway

  books-service:
    build: book-microservice/
    environment:
      IO_SERVICE_API_ROUTE: io-service/api
      NODE_ENV: development
    networks: 
      - laborator3-gateway
      - laborator3-books-io
    
  io-service:
    build: io-microservice/
    environment:
      PGUSER: admin
      PGPASSWORD: admin
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: books
      NODE_ENV: development
    networks:
      - laborator3-books-io
      - laborator3-io-db

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - laborator3-db-persistent-volume:/var/lib/postgresql/data
      - "${PWD}/database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
    networks:
      - laborator3-io-db
      - laborator3-db-adminer

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - laborator3-db-adminer

volumes:
  laborator3-db-persistent-volume:

networks:
  laborator3-gateway:
  laborator3-books-io:
  laborator3-io-db:
  laborator3-db-adminer:
