version: "3.8"

services:
  laborator2-api:
    image: mihaiconstantin98/idp:lab2-api
    environment:
      PGUSER: admin
      PGPASSWORD: admin
      PGDATABASE: books
      PGHOST: laborator2-db
      PGPORT: 5432
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 2
    ports:
      - "5555:80"
    networks:
      - laborator2-db-network
    depends_on:
      - laborator2-db

  laborator2-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: books
    volumes:
      - laborator2-db-persistent-volume:/var/lib/postgresql/data
      - "${PWD}/database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    networks: 
      - laborator2-db-network
      - laborator2-adminer-network
    
  laborator2-adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - laborator2-adminer-network
    depends_on:
      - laborator2-db

  laborator2-visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - 8081:8080
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  laborator2-db-persistent-volume:

networks:
  laborator2-db-network:
  laborator2-adminer-network:
