/**
 * Constantin Mihai - 321CD
 */

package utils;

public enum Severity {

    ABDOMINAL_PAIN_IMMEDIATE(60),
    ALLERGIC_REACTION_IMMEDIATE(50),
    BROKEN_BONES_IMMEDIATE(80),
    BURS_IMMEDIATE(40),
    CAR_ACCIDENT_IMMEDIATE(30),
    CUTS_IMMEDIATE(50),
    FOOD_POISONING_IMMEDIATE(50),
    HEART_ATTACK_IMMEDIATE(0),
    HEART_DISEASE_IMMEDIATE(40),
    HIGH_FEVER_IMMEDIATE(70),
    PNEUMONIA_IMMEDIATE(80),
    SPORT_INJURIES_IMMEDIATE(70),
    STROKE_IMMEDIATE(0),
    ABDOMINAL_PAIN_URGENT(40),
    ALLERGIC_REACTION_URGENT(30),
    BROKEN_BONES_URGENT(50),
    BURNS_URGENT(20),
    CAR_ACCIDENT_URGENT(20),
    CUTS_URGENT(30),
    HEART_ATTACK_URGENT(0),
    FOOD_POISONING_URGENT(20),
    HEART_DISEASE_URGENT(20),
    HIGH_FEVER_URGENT(40),
    PNEUMONIA_URGENT(50),
    SPORT_INJURIES_URGENT(50),
    STROKE_URGENT(0),
    ABDOMINAL_PAIN_LESS_URGENT(10),
    ALLERGIC_REACTION_LESS_URGENT(10),
    BROKEN_BONES_LESS_URGENT(20),
    BURNS_LESS_URGENT(10),
    CAR_ACCIDENT_LESS_URGENT(10),
    CUTS_LESS_URGENT(10),
    FOOD_POISONING_LESS_URGENT(0),
    HEART_ATTACK_LESS_URGENT(0),
    HEART_DISEASE_LESS_URGENT(10),
    HIGH_FEVER_LESS_URGENT(0),
    PNEUMONIA_LESS_URGENT(10),
    SPORT_INJURIES_LESS_URGENT(20),
    STROKE_LESS_URGENT(0);

    private int value;

    Severity(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
